# PERSISTENT VOLUME CLAIM DEFINITION
# ===
# this will encapsulate all resources so they live in a mini-universe of
# themselves.
---
apiVersion: v1 # note here, not all objects have the same apiVersion
kind: PersistentVolumeClaim
metadata:
  # Notice the `-pv-claim` (persistent-volume-claim) here for distinction. We'll 
  # be using this in the pods.
  name: sample-server-pv-claim
  # notice here, we want to use the same "universe" defined in sample-server.yml
  namespace: sample-server-ns
  # We'll use this later for filtering resources
  labels:
    target: sample-server
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 120Mi
